#!/usr/bin/env bash
# Install and configure HAProxy load balancer

echo -e "Updating and doing some minor checks...\n"

function install() {
	command -v "$1" &> /dev/null

	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

install haproxy # Install HAProxy

echo -e "\nSetting up some minor stuff.\n"

# Backup default server config file if it doesn't exist
if [ ! -f /etc/haproxy/haproxy_default.backup ]; then
    sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_default.backup
    echo "Backup of the original HAProxy configuration created."
else
    echo "Backup of the original HAProxy configuration already exists."
fi

# Define the server configuration
server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend dagmawi-tech-frontend
    bind *:80
    default_backend dagmawi-tech-backend

backend dagmawi-tech-backend
    balance roundrobin
    server 126066-web-01 34.232.71.175:80 check
    server 126066-web-02 54.175.144.183:80 check
"

# Apply the new configuration
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to start via init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

echo "Configured - Roundrobin on web-01 & web-02"

# Validate the HAProxy configuration before starting
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
if [ $? -ne 0 ]; then
    echo "HAProxy configuration is invalid. Please check the configuration."
    exit 1
fi

# Stop HAProxy if running, then start it
sudo service haproxy stop
sudo service haproxy start

# Check the status of the HAProxy service
sudo systemctl status haproxy.service

echo -e "web-01 web-02\nweb-01\nweb-02"
